/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Authority {
  'name' : string,
  'email' : string,
  'website' : string,
  'jurisdiction' : string,
  'phone' : string,
}
export type BodyType = { 'national' : null } |
  { 'state' : null } |
  { 'consumer' : null };
export type ExternalBlob = Uint8Array;
export type IssueType = { 'detailsNotDisplayed' : null } |
  { 'other' : string } |
  { 'pharmacistAbsent' : null } |
  { 'suspectedFake' : null };
export interface Observation {
  'gps' : [number, number],
  'presenceAnswers' : Array<string>,
  'timestamp' : Time,
  'photos' : Array<ExternalBlob>,
}
export interface Pharmacist {
  'name' : string,
  'registrationNumber' : string,
  'state' : string,
  'photo' : ExternalBlob,
}
export interface Pharmacy {
  'id' : string,
  'gpsCoordinates' : [number, number],
  'name' : string,
  'state' : string,
  'address' : string,
  'licenseNumber' : string,
}
export interface RegulatoryBody {
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
  'email' : string,
  'website' : string,
  'state' : [] | [string],
  'helpline' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
  'bodyType' : BodyType,
}
export interface Report {
  'id' : string,
  'status' : ReportStatus,
  'owner' : Principal,
  'createdAt' : Time,
  'user' : [] | [User],
  'issues' : Array<IssueType>,
  'updatedAt' : Time,
  'pharmacy' : Pharmacy,
  'observation' : Observation,
  'pharmacist' : Pharmacist,
}
export type ReportStatus = { 'resolved' : null } |
  { 'deleted' : null } |
  { 'emailSent' : null } |
  { 'draft' : null };
export type Time = bigint;
export interface User {
  'id' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAuthority' : ActorMethod<[string, Authority], undefined>,
  'addEducationContent' : ActorMethod<[string, string], undefined>,
  'addFaq' : ActorMethod<[string, string], undefined>,
  'addOrUpdateRegulatoryBody' : ActorMethod<
    [string, RegulatoryBody],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<[Report], string>,
  'deleteRegulatoryBody' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'getAllEducationContent' : ActorMethod<[], Array<[string, string]>>,
  'getAllFaq' : ActorMethod<[], Array<[string, string]>>,
  'getAllRegulatoryBodies' : ActorMethod<[], Array<RegulatoryBody>>,
  'getAuthoritiesByState' : ActorMethod<[string], Array<Authority>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEducationContent' : ActorMethod<[string], [] | [string]>,
  'getFaq' : ActorMethod<[string], [] | [string]>,
  'getRegulatoryBodiesByState' : ActorMethod<[string], Array<RegulatoryBody>>,
  'getRegulatoryBodiesByType' : ActorMethod<[BodyType], Array<RegulatoryBody>>,
  'getRegulatoryBody' : ActorMethod<[string], [] | [RegulatoryBody]>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReport' : ActorMethod<[string, Report], undefined>,
  'updateReportStatus' : ActorMethod<[string, ReportStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];