/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Authority = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'jurisdiction' : IDL.Text,
  'phone' : IDL.Text,
});
export const BodyType = IDL.Variant({
  'national' : IDL.Null,
  'state' : IDL.Null,
  'consumer' : IDL.Null,
});
export const RegulatoryBody = IDL.Record({
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'helpline' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'bodyType' : BodyType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'deleted' : IDL.Null,
  'emailSent' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const User = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const IssueType = IDL.Variant({
  'detailsNotDisplayed' : IDL.Null,
  'other' : IDL.Text,
  'pharmacistAbsent' : IDL.Null,
  'suspectedFake' : IDL.Null,
});
export const Pharmacy = IDL.Record({
  'id' : IDL.Text,
  'gpsCoordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'licenseNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Observation = IDL.Record({
  'gps' : IDL.Tuple(IDL.Float64, IDL.Float64),
  'presenceAnswers' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'photos' : IDL.Vec(ExternalBlob),
});
export const Pharmacist = IDL.Record({
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'state' : IDL.Text,
  'photo' : ExternalBlob,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'status' : ReportStatus,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'user' : IDL.Opt(User),
  'issues' : IDL.Vec(IssueType),
  'updatedAt' : Time,
  'pharmacy' : Pharmacy,
  'observation' : Observation,
  'pharmacist' : Pharmacist,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAuthority' : IDL.Func([IDL.Text, Authority], [], []),
  'addEducationContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFaq' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateRegulatoryBody' : IDL.Func([IDL.Text, RegulatoryBody], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func([Report], [IDL.Text], []),
  'deleteRegulatoryBody' : IDL.Func([IDL.Text], [], []),
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'getAllEducationContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllFaq' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllRegulatoryBodies' : IDL.Func([], [IDL.Vec(RegulatoryBody)], ['query']),
  'getAuthoritiesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Authority)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEducationContent' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getFaq' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getRegulatoryBodiesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RegulatoryBody)],
      ['query'],
    ),
  'getRegulatoryBodiesByType' : IDL.Func(
      [BodyType],
      [IDL.Vec(RegulatoryBody)],
      ['query'],
    ),
  'getRegulatoryBody' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RegulatoryBody)],
      ['query'],
    ),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReport' : IDL.Func([IDL.Text, Report], [], []),
  'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Authority = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'jurisdiction' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BodyType = IDL.Variant({
    'national' : IDL.Null,
    'state' : IDL.Null,
    'consumer' : IDL.Null,
  });
  const RegulatoryBody = IDL.Record({
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'helpline' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'bodyType' : BodyType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'deleted' : IDL.Null,
    'emailSent' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const User = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const IssueType = IDL.Variant({
    'detailsNotDisplayed' : IDL.Null,
    'other' : IDL.Text,
    'pharmacistAbsent' : IDL.Null,
    'suspectedFake' : IDL.Null,
  });
  const Pharmacy = IDL.Record({
    'id' : IDL.Text,
    'gpsCoordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'licenseNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Observation = IDL.Record({
    'gps' : IDL.Tuple(IDL.Float64, IDL.Float64),
    'presenceAnswers' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const Pharmacist = IDL.Record({
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'state' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'status' : ReportStatus,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'user' : IDL.Opt(User),
    'issues' : IDL.Vec(IssueType),
    'updatedAt' : Time,
    'pharmacy' : Pharmacy,
    'observation' : Observation,
    'pharmacist' : Pharmacist,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAuthority' : IDL.Func([IDL.Text, Authority], [], []),
    'addEducationContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFaq' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateRegulatoryBody' : IDL.Func([IDL.Text, RegulatoryBody], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func([Report], [IDL.Text], []),
    'deleteRegulatoryBody' : IDL.Func([IDL.Text], [], []),
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'getAllEducationContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllFaq' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllRegulatoryBodies' : IDL.Func(
        [],
        [IDL.Vec(RegulatoryBody)],
        ['query'],
      ),
    'getAuthoritiesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Authority)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEducationContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getFaq' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getRegulatoryBodiesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RegulatoryBody)],
        ['query'],
      ),
    'getRegulatoryBodiesByType' : IDL.Func(
        [BodyType],
        [IDL.Vec(RegulatoryBody)],
        ['query'],
      ),
    'getRegulatoryBody' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RegulatoryBody)],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReport' : IDL.Func([IDL.Text, Report], [], []),
    'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };