/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type IssueType = {
    __kind__: "detailsNotDisplayed";
    detailsNotDisplayed: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "pharmacistAbsent";
    pharmacistAbsent: null;
} | {
    __kind__: "suspectedFake";
    suspectedFake: null;
};
export interface User {
    id: string;
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Observation {
    gps: [number, number];
    presenceAnswers: Array<string>;
    timestamp: Time;
    photos: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: string;
    status: ReportStatus;
    owner: Principal;
    createdAt: Time;
    user?: User;
    issues: Array<IssueType>;
    updatedAt: Time;
    pharmacy: Pharmacy;
    observation: Observation;
    pharmacist: Pharmacist;
}
export interface RegulatoryBody {
    displayOrder: bigint;
    name: string;
    description: string;
    email: string;
    website: string;
    state?: string;
    helpline?: string;
    address?: string;
    phone: string;
    bodyType: BodyType;
}
export interface Pharmacy {
    id: string;
    gpsCoordinates: [number, number];
    name: string;
    state: string;
    address: string;
    licenseNumber: string;
}
export interface Authority {
    name: string;
    email: string;
    website: string;
    jurisdiction: string;
    phone: string;
}
export interface Pharmacist {
    name: string;
    registrationNumber: string;
    state: string;
    photo: ExternalBlob;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BodyType {
    national = "national",
    state = "state",
    consumer = "consumer"
}
export enum ReportStatus {
    resolved = "resolved",
    deleted = "deleted",
    emailSent = "emailSent",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAuthority(state: string, authority: Authority): Promise<void>;
    addEducationContent(key: string, content: string): Promise<void>;
    addFaq(key: string, content: string): Promise<void>;
    addOrUpdateRegulatoryBody(id: string, body: RegulatoryBody): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReport(report: Report): Promise<string>;
    deleteRegulatoryBody(id: string): Promise<void>;
    deleteReport(id: string): Promise<void>;
    getAllEducationContent(): Promise<Array<[string, string]>>;
    getAllFaq(): Promise<Array<[string, string]>>;
    getAllRegulatoryBodies(): Promise<Array<RegulatoryBody>>;
    getAuthoritiesByState(state: string): Promise<Array<Authority>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEducationContent(key: string): Promise<string | null>;
    getFaq(key: string): Promise<string | null>;
    getRegulatoryBodiesByState(state: string): Promise<Array<RegulatoryBody>>;
    getRegulatoryBodiesByType(bodyType: BodyType): Promise<Array<RegulatoryBody>>;
    getRegulatoryBody(id: string): Promise<RegulatoryBody | null>;
    getReport(id: string): Promise<Report | null>;
    getReports(): Promise<Array<Report>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateReport(id: string, updatedReport: Report): Promise<void>;
    updateReportStatus(id: string, status: ReportStatus): Promise<void>;
}
import type { BodyType as _BodyType, ExternalBlob as _ExternalBlob, IssueType as _IssueType, Observation as _Observation, Pharmacist as _Pharmacist, Pharmacy as _Pharmacy, RegulatoryBody as _RegulatoryBody, Report as _Report, ReportStatus as _ReportStatus, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAuthority(arg0: string, arg1: Authority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuthority(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuthority(arg0, arg1);
            return result;
        }
    }
    async addEducationContent(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducationContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducationContent(arg0, arg1);
            return result;
        }
    }
    async addFaq(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFaq(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFaq(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateRegulatoryBody(arg0: string, arg1: RegulatoryBody): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateRegulatoryBody(arg0, to_candid_RegulatoryBody_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateRegulatoryBody(arg0, to_candid_RegulatoryBody_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReport(arg0: Report): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(await to_candid_Report_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(await to_candid_Report_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteRegulatoryBody(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegulatoryBody(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegulatoryBody(arg0);
            return result;
        }
    }
    async deleteReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getAllEducationContent(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEducationContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEducationContent();
            return result;
        }
    }
    async getAllFaq(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFaq();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFaq();
            return result;
        }
    }
    async getAllRegulatoryBodies(): Promise<Array<RegulatoryBody>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegulatoryBodies();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegulatoryBodies();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthoritiesByState(arg0: string): Promise<Array<Authority>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthoritiesByState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthoritiesByState(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEducationContent(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducationContent(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducationContent(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFaq(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaq(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaq(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegulatoryBodiesByState(arg0: string): Promise<Array<RegulatoryBody>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegulatoryBodiesByState(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegulatoryBodiesByState(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegulatoryBodiesByType(arg0: BodyType): Promise<Array<RegulatoryBody>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegulatoryBodiesByType(to_candid_BodyType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegulatoryBodiesByType(to_candid_BodyType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegulatoryBody(arg0: string): Promise<RegulatoryBody | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegulatoryBody(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegulatoryBody(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateReport(arg0: string, arg1: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0, await to_candid_Report_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0, await to_candid_Report_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReportStatus(arg0: string, arg1: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BodyType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyType): BodyType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IssueType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueType): IssueType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_Observation_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Observation): Promise<Observation> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_Pharmacist_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pharmacist): Promise<Pharmacist> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_RegulatoryBody_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegulatoryBody): RegulatoryBody {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Report_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Promise<Report> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RegulatoryBody]): RegulatoryBody | null {
    return value.length === 0 ? null : from_candid_RegulatoryBody_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Promise<Report | null> {
    return value.length === 0 ? null : await from_candid_Report_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayOrder: bigint;
    name: string;
    description: string;
    email: string;
    website: string;
    state: [] | [string];
    helpline: [] | [string];
    address: [] | [string];
    phone: string;
    bodyType: _BodyType;
}): {
    displayOrder: bigint;
    name: string;
    description: string;
    email: string;
    website: string;
    state?: string;
    helpline?: string;
    address?: string;
    phone: string;
    bodyType: BodyType;
} {
    return {
        displayOrder: value.displayOrder,
        name: value.name,
        description: value.description,
        email: value.email,
        website: value.website,
        state: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.state)),
        helpline: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.helpline)),
        address: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.address)),
        phone: value.phone,
        bodyType: from_candid_BodyType_n31(_uploadFile, _downloadFile, value.bodyType)
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReportStatus;
    owner: Principal;
    createdAt: _Time;
    user: [] | [_User];
    issues: Array<_IssueType>;
    updatedAt: _Time;
    pharmacy: _Pharmacy;
    observation: _Observation;
    pharmacist: _Pharmacist;
}): Promise<{
    id: string;
    status: ReportStatus;
    owner: Principal;
    createdAt: Time;
    user?: User;
    issues: Array<IssueType>;
    updatedAt: Time;
    pharmacy: Pharmacy;
    observation: Observation;
    pharmacist: Pharmacist;
}> {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n40(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        user: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.user)),
        issues: from_candid_vec_n43(_uploadFile, _downloadFile, value.issues),
        updatedAt: value.updatedAt,
        pharmacy: value.pharmacy,
        observation: await from_candid_Observation_n46(_uploadFile, _downloadFile, value.observation),
        pharmacist: await from_candid_Pharmacist_n50(_uploadFile, _downloadFile, value.pharmacist)
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gps: [number, number];
    presenceAnswers: Array<string>;
    timestamp: _Time;
    photos: Array<_ExternalBlob>;
}): Promise<{
    gps: [number, number];
    presenceAnswers: Array<string>;
    timestamp: Time;
    photos: Array<ExternalBlob>;
}> {
    return {
        gps: value.gps,
        presenceAnswers: value.presenceAnswers,
        timestamp: value.timestamp,
        photos: await from_candid_vec_n48(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    registrationNumber: string;
    state: string;
    photo: _ExternalBlob;
}): Promise<{
    name: string;
    registrationNumber: string;
    state: string;
    photo: ExternalBlob;
}> {
    return {
        name: value.name,
        registrationNumber: value.registrationNumber,
        state: value.state,
        photo: await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value.photo)
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    national: null;
} | {
    state: null;
} | {
    consumer: null;
}): BodyType {
    return "national" in value ? BodyType.national : "state" in value ? BodyType.state : "consumer" in value ? BodyType.consumer : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    deleted: null;
} | {
    emailSent: null;
} | {
    draft: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "deleted" in value ? ReportStatus.deleted : "emailSent" in value ? ReportStatus.emailSent : "draft" in value ? ReportStatus.draft : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detailsNotDisplayed: null;
} | {
    other: string;
} | {
    pharmacistAbsent: null;
} | {
    suspectedFake: null;
}): {
    __kind__: "detailsNotDisplayed";
    detailsNotDisplayed: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "pharmacistAbsent";
    pharmacistAbsent: null;
} | {
    __kind__: "suspectedFake";
    suspectedFake: null;
} {
    return "detailsNotDisplayed" in value ? {
        __kind__: "detailsNotDisplayed",
        detailsNotDisplayed: value.detailsNotDisplayed
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "pharmacistAbsent" in value ? {
        __kind__: "pharmacistAbsent",
        pharmacistAbsent: value.pharmacistAbsent
    } : "suspectedFake" in value ? {
        __kind__: "suspectedFake",
        suspectedFake: value.suspectedFake
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegulatoryBody>): Array<RegulatoryBody> {
    return value.map((x)=>from_candid_RegulatoryBody_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IssueType>): Array<IssueType> {
    return value.map((x)=>from_candid_IssueType_n44(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Promise<Array<Report>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Report_n38(_uploadFile, _downloadFile, x)));
}
function to_candid_BodyType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyType): _BodyType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IssueType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueType): _IssueType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_Observation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Observation): Promise<_Observation> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Pharmacist_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pharmacist): Promise<_Pharmacist> {
    return await to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_RegulatoryBody_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegulatoryBody): _RegulatoryBody {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_Report_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Report): Promise<_Report> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ReportStatus;
    owner: Principal;
    createdAt: Time;
    user?: User;
    issues: Array<IssueType>;
    updatedAt: Time;
    pharmacy: Pharmacy;
    observation: Observation;
    pharmacist: Pharmacist;
}): Promise<{
    id: string;
    status: _ReportStatus;
    owner: Principal;
    createdAt: _Time;
    user: [] | [_User];
    issues: Array<_IssueType>;
    updatedAt: _Time;
    pharmacy: _Pharmacy;
    observation: _Observation;
    pharmacist: _Pharmacist;
}> {
    return {
        id: value.id,
        status: to_candid_ReportStatus_n16(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        user: value.user ? candid_some(value.user) : candid_none(),
        issues: to_candid_vec_n18(_uploadFile, _downloadFile, value.issues),
        updatedAt: value.updatedAt,
        pharmacy: value.pharmacy,
        observation: await to_candid_Observation_n21(_uploadFile, _downloadFile, value.observation),
        pharmacist: await to_candid_Pharmacist_n25(_uploadFile, _downloadFile, value.pharmacist)
    };
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gps: [number, number];
    presenceAnswers: Array<string>;
    timestamp: Time;
    photos: Array<ExternalBlob>;
}): Promise<{
    gps: [number, number];
    presenceAnswers: Array<string>;
    timestamp: _Time;
    photos: Array<_ExternalBlob>;
}> {
    return {
        gps: value.gps,
        presenceAnswers: value.presenceAnswers,
        timestamp: value.timestamp,
        photos: await to_candid_vec_n23(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    registrationNumber: string;
    state: string;
    photo: ExternalBlob;
}): Promise<{
    name: string;
    registrationNumber: string;
    state: string;
    photo: _ExternalBlob;
}> {
    return {
        name: value.name,
        registrationNumber: value.registrationNumber,
        state: value.state,
        photo: await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.photo)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayOrder: bigint;
    name: string;
    description: string;
    email: string;
    website: string;
    state?: string;
    helpline?: string;
    address?: string;
    phone: string;
    bodyType: BodyType;
}): {
    displayOrder: bigint;
    name: string;
    description: string;
    email: string;
    website: string;
    state: [] | [string];
    helpline: [] | [string];
    address: [] | [string];
    phone: string;
    bodyType: _BodyType;
} {
    return {
        displayOrder: value.displayOrder,
        name: value.name,
        description: value.description,
        email: value.email,
        website: value.website,
        state: value.state ? candid_some(value.state) : candid_none(),
        helpline: value.helpline ? candid_some(value.helpline) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone,
        bodyType: to_candid_BodyType_n10(_uploadFile, _downloadFile, value.bodyType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyType): {
    national: null;
} | {
    state: null;
} | {
    consumer: null;
} {
    return value == BodyType.national ? {
        national: null
    } : value == BodyType.state ? {
        state: null
    } : value == BodyType.consumer ? {
        consumer: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    deleted: null;
} | {
    emailSent: null;
} | {
    draft: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.deleted ? {
        deleted: null
    } : value == ReportStatus.emailSent ? {
        emailSent: null
    } : value == ReportStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "detailsNotDisplayed";
    detailsNotDisplayed: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "pharmacistAbsent";
    pharmacistAbsent: null;
} | {
    __kind__: "suspectedFake";
    suspectedFake: null;
}): {
    detailsNotDisplayed: null;
} | {
    other: string;
} | {
    pharmacistAbsent: null;
} | {
    suspectedFake: null;
} {
    return value.__kind__ === "detailsNotDisplayed" ? {
        detailsNotDisplayed: value.detailsNotDisplayed
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "pharmacistAbsent" ? {
        pharmacistAbsent: value.pharmacistAbsent
    } : value.__kind__ === "suspectedFake" ? {
        suspectedFake: value.suspectedFake
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<IssueType>): Array<_IssueType> {
    return value.map((x)=>to_candid_IssueType_n19(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
